apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../gke
patches:
  - target:
      kind: LeaderWorkerSet
      name: wide-ep-llm-d-decode
    patch: |-
      apiVersion: leaderworkerset.x-k8s.io/v1
      kind: LeaderWorkerSet
      metadata:
        name: wide-ep-llm-d-decode
      spec:
        leaderWorkerTemplate:
          workerTemplate:
            spec:
              volumes:
                - name: dshm
                  emptyDir:
                    medium: Memory
                    sizeLimit: 64Gi
              containers:
                - name: vllm
                  env:
                    - name: DP_SIZE_LOCAL
                      value: "4"
                    - name: VLLM_MODEL
                      value: "nvidia/DeepSeek-R1-0528-NVFP4-v2"
                    - name: KV_CACHE_MEMORY_BYTES
                      value: "63000000000"
                    - name: BASH_ENV
                      value: "/usr/local/gib/scripts/set_nccl_env.sh"
  - target:
      kind: LeaderWorkerSet
      name: wide-ep-llm-d-prefill
    patch: |-
      apiVersion: leaderworkerset.x-k8s.io/v1
      kind: LeaderWorkerSet
      metadata:
        name: wide-ep-llm-d-prefill
      spec:
        leaderWorkerTemplate:
          workerTemplate:
            spec:
              volumes:
                - name: dshm
                  emptyDir:
                    medium: Memory
                    sizeLimit: 64Gi
              containers:
                - name: vllm
                  env:
                    - name: DP_SIZE_LOCAL
                      value: "4"
                    - name: VLLM_MODEL
                      value: "nvidia/DeepSeek-R1-0528-NVFP4-v2"
                    - name: KV_CACHE_MEMORY_BYTES
                      value: "45000000000"
                    - name: BASH_ENV
                      value: "/usr/local/gib/scripts/set_nccl_env.sh"
