apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/torch-tpu

namePrefix: precise-prefix-cache-routing-tpu-v7-torch-tpu-

labels:
  - pairs:
      llm-d.ai/guide: precise-prefix-cache-routing
      llm-d.ai/model: Qwen3-Coder-480B-A35B-Instruct-FP8
      llm-d.ai/accelerator-variant: tpu-v7
      llm-d.ai/accelerator-vendor: google
      llm-d.ai/engine-type: torch-tpu
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
