apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../agentic-serving/modelserver/tpu/torch-tpu

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
    includeSelectors: true
    includeTemplates: true
