apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: us-central1-docker.pkg.dev/llm-d-scale/gateway-api-inference-extension/torchtpu-vllm-prod
    newTag: latest
