{
 "title": "Inference Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "# Inferece Gateway Dashboard\n\nPlease see https://github.com/kubernetes-sigs/gateway-api-inference-extension/tree/main/pkg/epp/metrics for more details of underlying metrics used in the dashboard."
   }
  },
  {
   "title": "Inference Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average KV Cache Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(name) (llmd_inference_scheduler_average_kv_cache_utilization)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 4 },
     "targets": [
      {
       "expr": "sum by(name) (llmd_inference_scheduler_average_queue_size)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue Size Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by(name, model_server_endpoint, pod) (llmd_inference_scheduler_per_endpoint_queue_size)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Inference Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "E2E Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(inference_model_request_duration_seconds_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(inference_model_request_duration_seconds_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(inference_model_request_duration_seconds_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Request / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by(model_name, target_model_name) (rate(inference_model_request_total{}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Error / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 13 },
     "targets": [
      {
       "expr": "sum by(error_code, model_name, target_model_name) (rate(inference_model_request_error_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(inference_model_request_sizes_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(inference_model_request_sizes_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(inference_model_request_sizes_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(inference_model_response_sizes_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(inference_model_response_sizes_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(inference_model_response_sizes_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Input Token Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(inference_model_input_tokens_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(inference_model_input_tokens_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(inference_model_input_tokens_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Output Token Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 29 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(inference_model_output_tokens_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(inference_model_output_tokens_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(inference_model_output_tokens_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "vLLM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by(model_name) (rate(vllm:prompt_tokens_total[$__rate_interval]))",
       "legendFormat": "Prompt Tokens/Sec"
      },
      {
       "expr": "sum by(model_name) (rate(vllm:generation_tokens_total[$__rate_interval]))",
       "legendFormat": "Generation Tokens/Sec"
      }
     ]
    },
    {
     "title": "E2E Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 60 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Time Per Output Token Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Time To First Token Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 67 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  }
 ]
}