apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/default

components:
  - ../../../../../recipes/modelserver/components/images/torch-tpu

patches:
  - path: patch-vllm.yaml
