inferenceExtension:
  replicas: 1
  image:
    registry: ghcr.io/llm-d
    repository: llm-d-router-endpoint-picker-dev
    tag: main
  extProcPort: 9002
  flags:
    v: 1
  pluginsConfigFile: "custom-plugins.yaml"
  pluginsCustomConfig:
    custom-plugins.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: disagg-headers-handler
      - type: always-disagg-pd-decider
      - type: disagg-profile-handler
        parameters:
          deciderPluginName: always-disagg-pd-decider
      - type: prefill-filter
      - type: decode-filter
      - type: prefix-cache-scorer
      - name: active-request-scorer
      - name: queue-scorer
      schedulingProfiles:
      - name: prefill
        plugins:
        - pluginRef: prefill-filter
        - pluginRef: prefix-cache-scorer
          weight: 3
        - pluginRef: active-request-scorer
          weight: 2
        - pluginRef: queue-scorer
          weight: 2
      - name: decode
        plugins:
        - pluginRef: decode-filter
        - pluginRef: active-request-scorer
          weight: 1
        - pluginRef: queue-scorer
          weight: 1

  monitoring:
    interval: "10s"
    prometheus:
      enabled: true
      auth:
        enabled: true
        secretName: wide-ep-gateway-sa-metrics-reader-secret

inferencePool:
  targetPorts:
    - number: 8000
    - number: 8001
    - number: 8002
    - number: 8003
  modelServerType: vllm
  modelServerProtocol: http
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "wide-ep-lws"
      llm-d.ai/model: nvidia/DeepSeek-R1-0528-NVFP4-v2

provider:
  name: istio
  istio:
    destinationRule:
      host: llm-d-infpool-epp
      trafficPolicy:
        tls:
          mode: SIMPLE
          insecureSkipVerify: true
        connectionPool:
          http:
            http1MaxPendingRequests: 256000
            maxRequestsPerConnection: 256000
            http2MaxRequests: 256000
            idleTimeout: "900s"
          tcp:
            maxConnections: 256000
            maxConnectionDuration: "1800s"
            connectTimeout: "900s"
