apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../gke-common

images:
  - name: ghcr.io/llm-d/llm-d-cuda
    newName: ghcr.io/llm-d/llm-d-cuda-dev
    newTag: pr-1769

patches:
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/affinity/nodeAffinity
        value:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-accelerator
                    operator: In
                    values:
                      - nvidia-b200
  - target:
      kind: LeaderWorkerSet
      name: wide-ep-llm-d-decode
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: KV_CACHE_MEMORY_BYTES
          value: "50000000000"
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: NCCL_TUNER_CONFIG_PATH
          value: "/usr/local/gib/configs/tuner_config_a4.txtpb"
  - target:
      kind: LeaderWorkerSet
      name: wide-ep-llm-d-prefill
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: NCCL_TUNER_CONFIG_PATH
          value: "/usr/local/gib/configs/tuner_config_a4.txtpb"
