apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: optimized-baseline
  namespace: torch-tpu-test
spec:
  targetPorts:
  - number: 8000
  selector:
    matchLabels:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/model: Qwen3-32B
      llm-d.ai/role: decode
  endpointPickerRef:
    name: optimized-baseline-epp
    port:
      number: 9002
