apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 2
  template:
    metadata:
      labels:
        llm-d.ai/engine-type: vllm
    spec:
      imagePullSecrets:
        - name: gcr-json-key
        - name: gcr-json-key-central
      nodeSelector:
        cloud.google.com/gke-tpu-topology: "2x4"
        cloud.google.com/gke-tpu-accelerator: "tpu-v6e-slice"
      initContainers:
        - name: tpu-node-setup
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              sysctl -w vm.max_map_count=33554432
              if [ -f /sys/module/vfio_iommu_type1/parameters/dma_entry_limit ]; then
                echo 8000000 > /sys/module/vfio_iommu_type1/parameters/dma_entry_limit
                echo "Successfully increased dma_entry_limit to 8000000"
              fi
          securityContext:
            privileged: true
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-32B"
            - "--port=8000"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=8"
            - "--attention-backend=CUSTOM"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
          resources:
            limits:
              google.com/tpu: "8"
            requests:
              google.com/tpu: "8"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: vllm-config
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "64Gi"
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: vllm-config
          emptyDir: {}
