name: Test Secret
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        run: |
          if [ -z "${{ secrets.GKE_SA_KEY }}" ]; then
            echo "Secret is EMPTY in caller!"
          else
            echo "Secret is NOT empty in caller!"
            echo "Length: ${#SECRET}"
          fi
        env:
          SECRET: ${{ secrets.GKE_SA_KEY }}
